game: main.o image.o texte.o buttons.o minimap.o enigme.o enigmeif.o players.o tools.o ES.o bounding_box.o tic.o sauv.o
	gcc main.o image.o texte.o buttons.o minimap.o enigme.o enigmeif.o players.o tools.o ES.o bounding_box.o tic.o sauv.o -o game -lSDL -lSDL_ttf -g -lSDL_image -lSDL_mixer
main.o: main.c
	gcc -c main.c -g
image.o: image.c
	gcc -c image.c -g
texte.o: texte.c
	gcc -c texte.c -g
buttons.o: buttons.c
	gcc -c buttons.c -g
minimap.o: minimap.c
	gcc -c minimap.c -g
enigme.o: enigme.c
	gcc -c enigme.c -g
ES.o: ES.c
	gcc -c ES.c -g
bounding_box.o: bounding_box.c
	gcc -c bounding_box.c -g
enigmeif.o: enigmeif.c
	gcc -c enigmeif.c -g
players.o: players.c
	gcc -c players.c -g
tools.o: tools.c
	gcc -c tools.c -g
tic.o: tic.c
	gcc -c tic.c -g
sauv.o: sauv.c
	gcc -c sauv.c -g
